# coding: utf-8

"""
    Billforward API

    This is documentation for the Billforward API. You can find out more at billforward.io.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@billforward.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import billforward
from billforward.api.avatax_api import AvataxApi  # noqa: E501
from billforward.rest import ApiException


class TestAvataxApi(unittest.TestCase):
    """AvataxApi unit test stubs"""

    def setUp(self):
        self.api = AvataxApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_avatax_configuration(self):
        """Test case for create_avatax_configuration

        """
        pass

    def test_get_avatax_configuration(self):
        """Test case for get_avatax_configuration

        """
        pass

    def test_ping(self):
        """Test case for ping

        """
        pass

    def test_update_avatax_configuration(self):
        """Test case for update_avatax_configuration

        """
        pass


if __name__ == '__main__':
    unittest.main()
