# coding: utf-8

"""
    Billforward API

    This is documentation for the Billforward API. You can find out more at billforward.io.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@billforward.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import billforward
from billforward.models.user_creation_request import UserCreationRequest  # noqa: E501
from billforward.rest import ApiException


class TestUserCreationRequest(unittest.TestCase):
    """UserCreationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserCreationRequest(self):
        """Test UserCreationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = billforward.models.user_creation_request.UserCreationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
