# coding: utf-8

"""
    Billforward API

    This is documentation for the Billforward API. You can find out more at billforward.io.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@billforward.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FixedTermDefinition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created': 'datetime',
        'changed_by': 'str',
        'updated': 'datetime',
        'id': 'str',
        'organization_id': 'str',
        'product_rate_plan_id': 'str',
        'expiry_behaviour': 'str',
        'next_product_rate_plan_id': 'str',
        'first_term_periods': 'int',
        'subsequent_term_periods': 'int',
        'deleted': 'bool'
    }

    attribute_map = {
        'created': 'created',
        'changed_by': 'changedBy',
        'updated': 'updated',
        'id': 'id',
        'organization_id': 'organizationID',
        'product_rate_plan_id': 'productRatePlanID',
        'expiry_behaviour': 'expiryBehaviour',
        'next_product_rate_plan_id': 'nextProductRatePlanID',
        'first_term_periods': 'firstTermPeriods',
        'subsequent_term_periods': 'subsequentTermPeriods',
        'deleted': 'deleted'
    }

    def __init__(self, created=None, changed_by=None, updated=None, id=None, organization_id=None, product_rate_plan_id=None, expiry_behaviour=None, next_product_rate_plan_id=None, first_term_periods=None, subsequent_term_periods=None, deleted=None):  # noqa: E501
        """FixedTermDefinition - a model defined in Swagger"""  # noqa: E501
        self._created = None
        self._changed_by = None
        self._updated = None
        self._id = None
        self._organization_id = None
        self._product_rate_plan_id = None
        self._expiry_behaviour = None
        self._next_product_rate_plan_id = None
        self._first_term_periods = None
        self._subsequent_term_periods = None
        self._deleted = None
        self.discriminator = None
        if created is not None:
            self.created = created
        if changed_by is not None:
            self.changed_by = changed_by
        if updated is not None:
            self.updated = updated
        if id is not None:
            self.id = id
        if organization_id is not None:
            self.organization_id = organization_id
        if product_rate_plan_id is not None:
            self.product_rate_plan_id = product_rate_plan_id
        self.expiry_behaviour = expiry_behaviour
        if next_product_rate_plan_id is not None:
            self.next_product_rate_plan_id = next_product_rate_plan_id
        if first_term_periods is not None:
            self.first_term_periods = first_term_periods
        if subsequent_term_periods is not None:
            self.subsequent_term_periods = subsequent_term_periods
        if deleted is not None:
            self.deleted = deleted

    @property
    def created(self):
        """Gets the created of this FixedTermDefinition.  # noqa: E501


        :return: The created of this FixedTermDefinition.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this FixedTermDefinition.


        :param created: The created of this FixedTermDefinition.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def changed_by(self):
        """Gets the changed_by of this FixedTermDefinition.  # noqa: E501


        :return: The changed_by of this FixedTermDefinition.  # noqa: E501
        :rtype: str
        """
        return self._changed_by

    @changed_by.setter
    def changed_by(self, changed_by):
        """Sets the changed_by of this FixedTermDefinition.


        :param changed_by: The changed_by of this FixedTermDefinition.  # noqa: E501
        :type: str
        """

        self._changed_by = changed_by

    @property
    def updated(self):
        """Gets the updated of this FixedTermDefinition.  # noqa: E501


        :return: The updated of this FixedTermDefinition.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this FixedTermDefinition.


        :param updated: The updated of this FixedTermDefinition.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    @property
    def id(self):
        """Gets the id of this FixedTermDefinition.  # noqa: E501


        :return: The id of this FixedTermDefinition.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FixedTermDefinition.


        :param id: The id of this FixedTermDefinition.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def organization_id(self):
        """Gets the organization_id of this FixedTermDefinition.  # noqa: E501


        :return: The organization_id of this FixedTermDefinition.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this FixedTermDefinition.


        :param organization_id: The organization_id of this FixedTermDefinition.  # noqa: E501
        :type: str
        """

        self._organization_id = organization_id

    @property
    def product_rate_plan_id(self):
        """Gets the product_rate_plan_id of this FixedTermDefinition.  # noqa: E501


        :return: The product_rate_plan_id of this FixedTermDefinition.  # noqa: E501
        :rtype: str
        """
        return self._product_rate_plan_id

    @product_rate_plan_id.setter
    def product_rate_plan_id(self, product_rate_plan_id):
        """Sets the product_rate_plan_id of this FixedTermDefinition.


        :param product_rate_plan_id: The product_rate_plan_id of this FixedTermDefinition.  # noqa: E501
        :type: str
        """

        self._product_rate_plan_id = product_rate_plan_id

    @property
    def expiry_behaviour(self):
        """Gets the expiry_behaviour of this FixedTermDefinition.  # noqa: E501


        :return: The expiry_behaviour of this FixedTermDefinition.  # noqa: E501
        :rtype: str
        """
        return self._expiry_behaviour

    @expiry_behaviour.setter
    def expiry_behaviour(self, expiry_behaviour):
        """Sets the expiry_behaviour of this FixedTermDefinition.


        :param expiry_behaviour: The expiry_behaviour of this FixedTermDefinition.  # noqa: E501
        :type: str
        """
        if expiry_behaviour is None:
            raise ValueError("Invalid value for `expiry_behaviour`, must not be `None`")  # noqa: E501
        allowed_values = ["ExpireSubscription", "EvergreenSubscription", "RecurLatestPricing", "ChangePlan"]  # noqa: E501
        if expiry_behaviour not in allowed_values:
            raise ValueError(
                "Invalid value for `expiry_behaviour` ({0}), must be one of {1}"  # noqa: E501
                .format(expiry_behaviour, allowed_values)
            )

        self._expiry_behaviour = expiry_behaviour

    @property
    def next_product_rate_plan_id(self):
        """Gets the next_product_rate_plan_id of this FixedTermDefinition.  # noqa: E501


        :return: The next_product_rate_plan_id of this FixedTermDefinition.  # noqa: E501
        :rtype: str
        """
        return self._next_product_rate_plan_id

    @next_product_rate_plan_id.setter
    def next_product_rate_plan_id(self, next_product_rate_plan_id):
        """Sets the next_product_rate_plan_id of this FixedTermDefinition.


        :param next_product_rate_plan_id: The next_product_rate_plan_id of this FixedTermDefinition.  # noqa: E501
        :type: str
        """

        self._next_product_rate_plan_id = next_product_rate_plan_id

    @property
    def first_term_periods(self):
        """Gets the first_term_periods of this FixedTermDefinition.  # noqa: E501


        :return: The first_term_periods of this FixedTermDefinition.  # noqa: E501
        :rtype: int
        """
        return self._first_term_periods

    @first_term_periods.setter
    def first_term_periods(self, first_term_periods):
        """Sets the first_term_periods of this FixedTermDefinition.


        :param first_term_periods: The first_term_periods of this FixedTermDefinition.  # noqa: E501
        :type: int
        """

        self._first_term_periods = first_term_periods

    @property
    def subsequent_term_periods(self):
        """Gets the subsequent_term_periods of this FixedTermDefinition.  # noqa: E501


        :return: The subsequent_term_periods of this FixedTermDefinition.  # noqa: E501
        :rtype: int
        """
        return self._subsequent_term_periods

    @subsequent_term_periods.setter
    def subsequent_term_periods(self, subsequent_term_periods):
        """Sets the subsequent_term_periods of this FixedTermDefinition.


        :param subsequent_term_periods: The subsequent_term_periods of this FixedTermDefinition.  # noqa: E501
        :type: int
        """

        self._subsequent_term_periods = subsequent_term_periods

    @property
    def deleted(self):
        """Gets the deleted of this FixedTermDefinition.  # noqa: E501


        :return: The deleted of this FixedTermDefinition.  # noqa: E501
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """Sets the deleted of this FixedTermDefinition.


        :param deleted: The deleted of this FixedTermDefinition.  # noqa: E501
        :type: bool
        """

        self._deleted = deleted

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FixedTermDefinition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FixedTermDefinition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
