# coding: utf-8

"""
    Billforward API

    This is documentation for the Billforward API. You can find out more at billforward.io.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@billforward.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PricingComponentValueRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created': 'datetime',
        'value': 'int',
        'organization_id': 'str',
        'change_mode': 'str',
        'prorate': 'bool',
        'invoicing_type': 'str',
        'no_charge': 'bool'
    }

    attribute_map = {
        'created': 'created',
        'value': 'value',
        'organization_id': 'organizationID',
        'change_mode': 'changeMode',
        'prorate': 'prorate',
        'invoicing_type': 'invoicingType',
        'no_charge': 'noCharge'
    }

    def __init__(self, created=None, value=None, organization_id=None, change_mode=None, prorate=None, invoicing_type=None, no_charge=None):  # noqa: E501
        """PricingComponentValueRequest - a model defined in Swagger"""  # noqa: E501
        self._created = None
        self._value = None
        self._organization_id = None
        self._change_mode = None
        self._prorate = None
        self._invoicing_type = None
        self._no_charge = None
        self.discriminator = None
        if created is not None:
            self.created = created
        self.value = value
        if organization_id is not None:
            self.organization_id = organization_id
        if change_mode is not None:
            self.change_mode = change_mode
        if prorate is not None:
            self.prorate = prorate
        if invoicing_type is not None:
            self.invoicing_type = invoicing_type
        if no_charge is not None:
            self.no_charge = no_charge

    @property
    def created(self):
        """Gets the created of this PricingComponentValueRequest.  # noqa: E501


        :return: The created of this PricingComponentValueRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this PricingComponentValueRequest.


        :param created: The created of this PricingComponentValueRequest.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def value(self):
        """Gets the value of this PricingComponentValueRequest.  # noqa: E501


        :return: The value of this PricingComponentValueRequest.  # noqa: E501
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this PricingComponentValueRequest.


        :param value: The value of this PricingComponentValueRequest.  # noqa: E501
        :type: int
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def organization_id(self):
        """Gets the organization_id of this PricingComponentValueRequest.  # noqa: E501


        :return: The organization_id of this PricingComponentValueRequest.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this PricingComponentValueRequest.


        :param organization_id: The organization_id of this PricingComponentValueRequest.  # noqa: E501
        :type: str
        """

        self._organization_id = organization_id

    @property
    def change_mode(self):
        """Gets the change_mode of this PricingComponentValueRequest.  # noqa: E501


        :return: The change_mode of this PricingComponentValueRequest.  # noqa: E501
        :rtype: str
        """
        return self._change_mode

    @change_mode.setter
    def change_mode(self, change_mode):
        """Sets the change_mode of this PricingComponentValueRequest.


        :param change_mode: The change_mode of this PricingComponentValueRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["immediate", "delayed"]  # noqa: E501
        if change_mode not in allowed_values:
            raise ValueError(
                "Invalid value for `change_mode` ({0}), must be one of {1}"  # noqa: E501
                .format(change_mode, allowed_values)
            )

        self._change_mode = change_mode

    @property
    def prorate(self):
        """Gets the prorate of this PricingComponentValueRequest.  # noqa: E501


        :return: The prorate of this PricingComponentValueRequest.  # noqa: E501
        :rtype: bool
        """
        return self._prorate

    @prorate.setter
    def prorate(self, prorate):
        """Sets the prorate of this PricingComponentValueRequest.


        :param prorate: The prorate of this PricingComponentValueRequest.  # noqa: E501
        :type: bool
        """

        self._prorate = prorate

    @property
    def invoicing_type(self):
        """Gets the invoicing_type of this PricingComponentValueRequest.  # noqa: E501


        :return: The invoicing_type of this PricingComponentValueRequest.  # noqa: E501
        :rtype: str
        """
        return self._invoicing_type

    @invoicing_type.setter
    def invoicing_type(self, invoicing_type):
        """Sets the invoicing_type of this PricingComponentValueRequest.


        :param invoicing_type: The invoicing_type of this PricingComponentValueRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["Immediate", "Aggregated"]  # noqa: E501
        if invoicing_type not in allowed_values:
            raise ValueError(
                "Invalid value for `invoicing_type` ({0}), must be one of {1}"  # noqa: E501
                .format(invoicing_type, allowed_values)
            )

        self._invoicing_type = invoicing_type

    @property
    def no_charge(self):
        """Gets the no_charge of this PricingComponentValueRequest.  # noqa: E501


        :return: The no_charge of this PricingComponentValueRequest.  # noqa: E501
        :rtype: bool
        """
        return self._no_charge

    @no_charge.setter
    def no_charge(self, no_charge):
        """Sets the no_charge of this PricingComponentValueRequest.


        :param no_charge: The no_charge of this PricingComponentValueRequest.  # noqa: E501
        :type: bool
        """

        self._no_charge = no_charge

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PricingComponentValueRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PricingComponentValueRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
