# coding: utf-8

"""
    Billforward API

    This is documentation for the Billforward API. You can find out more at billforward.io.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@billforward.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StripeToken(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created': 'datetime',
        'changed_by': 'str',
        'updated': 'datetime',
        'id': 'str',
        'account_id': 'str',
        'card_details_id': 'str',
        'organization_id': 'str',
        'stripe_customer_id': 'str',
        'status': 'str',
        'deleted': 'bool'
    }

    attribute_map = {
        'created': 'created',
        'changed_by': 'changedBy',
        'updated': 'updated',
        'id': 'id',
        'account_id': 'accountID',
        'card_details_id': 'cardDetailsID',
        'organization_id': 'organizationID',
        'stripe_customer_id': 'stripeCustomerID',
        'status': 'status',
        'deleted': 'deleted'
    }

    def __init__(self, created=None, changed_by=None, updated=None, id=None, account_id=None, card_details_id=None, organization_id=None, stripe_customer_id=None, status=None, deleted=None):  # noqa: E501
        """StripeToken - a model defined in Swagger"""  # noqa: E501
        self._created = None
        self._changed_by = None
        self._updated = None
        self._id = None
        self._account_id = None
        self._card_details_id = None
        self._organization_id = None
        self._stripe_customer_id = None
        self._status = None
        self._deleted = None
        self.discriminator = None
        if created is not None:
            self.created = created
        if changed_by is not None:
            self.changed_by = changed_by
        if updated is not None:
            self.updated = updated
        if id is not None:
            self.id = id
        self.account_id = account_id
        if card_details_id is not None:
            self.card_details_id = card_details_id
        self.organization_id = organization_id
        self.stripe_customer_id = stripe_customer_id
        self.status = status
        self.deleted = deleted

    @property
    def created(self):
        """Gets the created of this StripeToken.  # noqa: E501


        :return: The created of this StripeToken.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this StripeToken.


        :param created: The created of this StripeToken.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def changed_by(self):
        """Gets the changed_by of this StripeToken.  # noqa: E501


        :return: The changed_by of this StripeToken.  # noqa: E501
        :rtype: str
        """
        return self._changed_by

    @changed_by.setter
    def changed_by(self, changed_by):
        """Sets the changed_by of this StripeToken.


        :param changed_by: The changed_by of this StripeToken.  # noqa: E501
        :type: str
        """

        self._changed_by = changed_by

    @property
    def updated(self):
        """Gets the updated of this StripeToken.  # noqa: E501


        :return: The updated of this StripeToken.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this StripeToken.


        :param updated: The updated of this StripeToken.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    @property
    def id(self):
        """Gets the id of this StripeToken.  # noqa: E501


        :return: The id of this StripeToken.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this StripeToken.


        :param id: The id of this StripeToken.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def account_id(self):
        """Gets the account_id of this StripeToken.  # noqa: E501


        :return: The account_id of this StripeToken.  # noqa: E501
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this StripeToken.


        :param account_id: The account_id of this StripeToken.  # noqa: E501
        :type: str
        """
        if account_id is None:
            raise ValueError("Invalid value for `account_id`, must not be `None`")  # noqa: E501

        self._account_id = account_id

    @property
    def card_details_id(self):
        """Gets the card_details_id of this StripeToken.  # noqa: E501


        :return: The card_details_id of this StripeToken.  # noqa: E501
        :rtype: str
        """
        return self._card_details_id

    @card_details_id.setter
    def card_details_id(self, card_details_id):
        """Sets the card_details_id of this StripeToken.


        :param card_details_id: The card_details_id of this StripeToken.  # noqa: E501
        :type: str
        """

        self._card_details_id = card_details_id

    @property
    def organization_id(self):
        """Gets the organization_id of this StripeToken.  # noqa: E501


        :return: The organization_id of this StripeToken.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this StripeToken.


        :param organization_id: The organization_id of this StripeToken.  # noqa: E501
        :type: str
        """
        if organization_id is None:
            raise ValueError("Invalid value for `organization_id`, must not be `None`")  # noqa: E501

        self._organization_id = organization_id

    @property
    def stripe_customer_id(self):
        """Gets the stripe_customer_id of this StripeToken.  # noqa: E501


        :return: The stripe_customer_id of this StripeToken.  # noqa: E501
        :rtype: str
        """
        return self._stripe_customer_id

    @stripe_customer_id.setter
    def stripe_customer_id(self, stripe_customer_id):
        """Sets the stripe_customer_id of this StripeToken.


        :param stripe_customer_id: The stripe_customer_id of this StripeToken.  # noqa: E501
        :type: str
        """
        if stripe_customer_id is None:
            raise ValueError("Invalid value for `stripe_customer_id`, must not be `None`")  # noqa: E501

        self._stripe_customer_id = stripe_customer_id

    @property
    def status(self):
        """Gets the status of this StripeToken.  # noqa: E501


        :return: The status of this StripeToken.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this StripeToken.


        :param status: The status of this StripeToken.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501
        allowed_values = ["Awaiting3dsVerification", "Verified", "DoesNotRequireVerification"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def deleted(self):
        """Gets the deleted of this StripeToken.  # noqa: E501


        :return: The deleted of this StripeToken.  # noqa: E501
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """Sets the deleted of this StripeToken.


        :param deleted: The deleted of this StripeToken.  # noqa: E501
        :type: bool
        """
        if deleted is None:
            raise ValueError("Invalid value for `deleted`, must not be `None`")  # noqa: E501

        self._deleted = deleted

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StripeToken, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StripeToken):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
