# coding: utf-8

"""
    Billforward API

    This is documentation for the Billforward API. You can find out more at billforward.io.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@billforward.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateEmailRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'password': 'str',
        'new_email': 'str',
        'confirm_new_email': 'str',
        'revoke_old_access_tokens': 'bool',
        'organization_id': 'str'
    }

    attribute_map = {
        'password': 'password',
        'new_email': 'newEmail',
        'confirm_new_email': 'confirmNewEmail',
        'revoke_old_access_tokens': 'revokeOldAccessTokens',
        'organization_id': 'organizationID'
    }

    def __init__(self, password=None, new_email=None, confirm_new_email=None, revoke_old_access_tokens=None, organization_id=None):  # noqa: E501
        """UpdateEmailRequest - a model defined in Swagger"""  # noqa: E501
        self._password = None
        self._new_email = None
        self._confirm_new_email = None
        self._revoke_old_access_tokens = None
        self._organization_id = None
        self.discriminator = None
        if password is not None:
            self.password = password
        if new_email is not None:
            self.new_email = new_email
        if confirm_new_email is not None:
            self.confirm_new_email = confirm_new_email
        if revoke_old_access_tokens is not None:
            self.revoke_old_access_tokens = revoke_old_access_tokens
        if organization_id is not None:
            self.organization_id = organization_id

    @property
    def password(self):
        """Gets the password of this UpdateEmailRequest.  # noqa: E501


        :return: The password of this UpdateEmailRequest.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this UpdateEmailRequest.


        :param password: The password of this UpdateEmailRequest.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def new_email(self):
        """Gets the new_email of this UpdateEmailRequest.  # noqa: E501


        :return: The new_email of this UpdateEmailRequest.  # noqa: E501
        :rtype: str
        """
        return self._new_email

    @new_email.setter
    def new_email(self, new_email):
        """Sets the new_email of this UpdateEmailRequest.


        :param new_email: The new_email of this UpdateEmailRequest.  # noqa: E501
        :type: str
        """

        self._new_email = new_email

    @property
    def confirm_new_email(self):
        """Gets the confirm_new_email of this UpdateEmailRequest.  # noqa: E501


        :return: The confirm_new_email of this UpdateEmailRequest.  # noqa: E501
        :rtype: str
        """
        return self._confirm_new_email

    @confirm_new_email.setter
    def confirm_new_email(self, confirm_new_email):
        """Sets the confirm_new_email of this UpdateEmailRequest.


        :param confirm_new_email: The confirm_new_email of this UpdateEmailRequest.  # noqa: E501
        :type: str
        """

        self._confirm_new_email = confirm_new_email

    @property
    def revoke_old_access_tokens(self):
        """Gets the revoke_old_access_tokens of this UpdateEmailRequest.  # noqa: E501


        :return: The revoke_old_access_tokens of this UpdateEmailRequest.  # noqa: E501
        :rtype: bool
        """
        return self._revoke_old_access_tokens

    @revoke_old_access_tokens.setter
    def revoke_old_access_tokens(self, revoke_old_access_tokens):
        """Sets the revoke_old_access_tokens of this UpdateEmailRequest.


        :param revoke_old_access_tokens: The revoke_old_access_tokens of this UpdateEmailRequest.  # noqa: E501
        :type: bool
        """

        self._revoke_old_access_tokens = revoke_old_access_tokens

    @property
    def organization_id(self):
        """Gets the organization_id of this UpdateEmailRequest.  # noqa: E501


        :return: The organization_id of this UpdateEmailRequest.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this UpdateEmailRequest.


        :param organization_id: The organization_id of this UpdateEmailRequest.  # noqa: E501
        :type: str
        """

        self._organization_id = organization_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateEmailRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateEmailRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
