# coding: utf-8

"""
    Billforward API

    This is documentation for the Billforward API. You can find out more at billforward.io.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@billforward.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Username(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created': 'datetime',
        'changed_by': 'str',
        'id': 'str',
        'user_id': 'str',
        'organization_id': 'str',
        'username': 'str',
        'first_name': 'str',
        'last_name': 'str',
        'profile_picture': 'str',
        'email': 'str'
    }

    attribute_map = {
        'created': 'created',
        'changed_by': 'changedBy',
        'id': 'id',
        'user_id': 'userID',
        'organization_id': 'organizationID',
        'username': 'username',
        'first_name': 'firstName',
        'last_name': 'lastName',
        'profile_picture': 'profilePicture',
        'email': 'email'
    }

    def __init__(self, created=None, changed_by=None, id=None, user_id=None, organization_id=None, username=None, first_name=None, last_name=None, profile_picture=None, email=None):  # noqa: E501
        """Username - a model defined in Swagger"""  # noqa: E501
        self._created = None
        self._changed_by = None
        self._id = None
        self._user_id = None
        self._organization_id = None
        self._username = None
        self._first_name = None
        self._last_name = None
        self._profile_picture = None
        self._email = None
        self.discriminator = None
        if created is not None:
            self.created = created
        if changed_by is not None:
            self.changed_by = changed_by
        if id is not None:
            self.id = id
        self.user_id = user_id
        self.organization_id = organization_id
        self.username = username
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if profile_picture is not None:
            self.profile_picture = profile_picture
        if email is not None:
            self.email = email

    @property
    def created(self):
        """Gets the created of this Username.  # noqa: E501


        :return: The created of this Username.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Username.


        :param created: The created of this Username.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def changed_by(self):
        """Gets the changed_by of this Username.  # noqa: E501


        :return: The changed_by of this Username.  # noqa: E501
        :rtype: str
        """
        return self._changed_by

    @changed_by.setter
    def changed_by(self, changed_by):
        """Sets the changed_by of this Username.


        :param changed_by: The changed_by of this Username.  # noqa: E501
        :type: str
        """

        self._changed_by = changed_by

    @property
    def id(self):
        """Gets the id of this Username.  # noqa: E501


        :return: The id of this Username.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Username.


        :param id: The id of this Username.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def user_id(self):
        """Gets the user_id of this Username.  # noqa: E501


        :return: The user_id of this Username.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this Username.


        :param user_id: The user_id of this Username.  # noqa: E501
        :type: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def organization_id(self):
        """Gets the organization_id of this Username.  # noqa: E501


        :return: The organization_id of this Username.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this Username.


        :param organization_id: The organization_id of this Username.  # noqa: E501
        :type: str
        """
        if organization_id is None:
            raise ValueError("Invalid value for `organization_id`, must not be `None`")  # noqa: E501

        self._organization_id = organization_id

    @property
    def username(self):
        """Gets the username of this Username.  # noqa: E501


        :return: The username of this Username.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this Username.


        :param username: The username of this Username.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def first_name(self):
        """Gets the first_name of this Username.  # noqa: E501


        :return: The first_name of this Username.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this Username.


        :param first_name: The first_name of this Username.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this Username.  # noqa: E501


        :return: The last_name of this Username.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this Username.


        :param last_name: The last_name of this Username.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def profile_picture(self):
        """Gets the profile_picture of this Username.  # noqa: E501


        :return: The profile_picture of this Username.  # noqa: E501
        :rtype: str
        """
        return self._profile_picture

    @profile_picture.setter
    def profile_picture(self, profile_picture):
        """Sets the profile_picture of this Username.


        :param profile_picture: The profile_picture of this Username.  # noqa: E501
        :type: str
        """

        self._profile_picture = profile_picture

    @property
    def email(self):
        """Gets the email of this Username.  # noqa: E501


        :return: The email of this Username.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this Username.


        :param email: The email of this Username.  # noqa: E501
        :type: str
        """

        self._email = email

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Username, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Username):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
